import { WeeklySchedule, Subject, Badge } from './types';

export const SYLLABUS_VERSION = '2026-AL-SL-V3';

export const INITIAL_SUBJECTS: Subject[] = [
  {
    id: 'maths',
    name: 'Combined Maths',
    score: 45,
    focus: 5,
    weakCount: 8,
    status: 'Critical',
    priorityScore: 0,
    readiness: 0,
    gradient: 'from-green-500/20 to-green-900/40',
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&q=80&w=800',
    examDate: '2026-07-15',
    notes: 'Weekly: Homework, Paper Review, Past Lesson Review, Missed Lesson Learning.',
    weeklyTasks: [
      { id: 'm1', title: 'Homework', completed: false },
      { id: 'm2', title: 'Paper Review (with past papers)', completed: false },
      { id: 'm3', title: 'Past Lesson Review', completed: false },
      { id: 'm4', title: 'Missed Lesson Learning & Practice (missed recording watch)', completed: false },
    ],
    topics: [
      { id: 'm1', title: '01. Real Number System', mastery: 60, image: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=400' },
      { id: 'm2', title: '02. Functions & Polynomials', mastery: 55, image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&q=80&w=400' },
      { id: 'm3', title: '03. Quadratic Equations', mastery: 70, image: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=400' },
      { id: 'm4', title: '04. Complex Numbers', mastery: 40, image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&q=80&w=400' },
      { id: 'm5', title: '05. Sequences & Series', mastery: 50, image: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=400' },
      { id: 'm6', title: '06. Binomial Expansion', mastery: 65, image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&q=80&w=400' },
      { id: 'm7', title: '07. Trigonometry', mastery: 35, image: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=400' },
      { id: 'm8', title: '08. Differentiation', mastery: 45, image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&q=80&w=400' },
      { id: 'm9', title: '09. Integration', mastery: 30, image: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=400' },
      { id: 'm10', title: '10. Coordinate Geometry', mastery: 50, image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&q=80&w=400' },
      { id: 'm11', title: '11. Vectors', mastery: 60, image: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=400' },
      { id: 'm12', title: '12. Statics (Forces)', mastery: 40, image: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&q=80&w=400' },
      { id: 'm13', title: '13. Dynamics (Motion)', mastery: 35, image: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?auto=format&fit=crop&q=80&w=400' },
      { id: 'm14', title: '14. Probability & Stats', mastery: 55, image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&q=80&w=400' },
    ]
  },
  {
    id: 'physics',
    name: 'Physics',
    score: 58,
    focus: 4,
    weakCount: 5,
    status: 'Weak',
    priorityScore: 0,
    readiness: 0,
    gradient: 'from-blue-500/20 to-blue-900/40',
    image: 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?auto=format&fit=crop&q=80&w=800',
    examDate: '2026-07-22',
    notes: 'Weekly: Homework, Paper Review, Past Lesson Review, Missed Lesson Learning, Practical Lesson.',
    weeklyTasks: [
      { id: 'p1', title: 'Homework', completed: false },
      { id: 'p2', title: 'Paper Review (with past papers)', completed: false },
      { id: 'p3', title: 'Past Lesson Review', completed: false },
      { id: 'p4', title: 'Missed Lesson Learning & Practice (missed recording watch)', completed: false },
      { id: 'p5', title: 'Physics Practical Lesson Learning & Practice', completed: false },
    ],
    topics: [
      { id: 'p1', title: '01. Units & Measurements', mastery: 85, image: 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?auto=format&fit=crop&q=80&w=400' },
      { id: 'p2', title: '02. Mechanics', mastery: 55, image: 'https://images.unsplash.com/photo-1535813543269-7328ec13954e?auto=format&fit=crop&q=80&w=400' },
      { id: 'p3', title: '03. Oscillations & Waves', mastery: 45, image: 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?auto=format&fit=crop&q=80&w=400' },
      { id: 'p4', title: '04. Thermal Physics', mastery: 60, image: 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?auto=format&fit=crop&q=80&w=400' },
      { id: 'p5', title: '05. Gravitational Fields', mastery: 50, image: 'https://images.unsplash.com/photo-1535813543269-7328ec13954e?auto=format&fit=crop&q=80&w=400' },
      { id: 'p6', title: '06. Electrostatic Fields', mastery: 40, image: 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?auto=format&fit=crop&q=80&w=400' },
      { id: 'p7', title: '07. Magnetic Fields', mastery: 35, image: 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?auto=format&fit=crop&q=80&w=400' },
      { id: 'p8', title: '08. Current Electricity', mastery: 55, image: 'https://images.unsplash.com/photo-1535813543269-7328ec13954e?auto=format&fit=crop&q=80&w=400' },
      { id: 'p9', title: '09. Electronics', mastery: 30, image: 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?auto=format&fit=crop&q=80&w=400' },
      { id: 'p10', title: '10. Radiation & Matter', mastery: 65, image: 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?auto=format&fit=crop&q=80&w=400' },
      { id: 'p11', title: '11. Properties of Matter', mastery: 50, image: 'https://images.unsplash.com/photo-1535813543269-7328ec13954e?auto=format&fit=crop&q=80&w=400' },
    ]
  },
  {
    id: 'chemistry',
    name: 'Chemistry',
    score: 68,
    focus: 4,
    weakCount: 3,
    status: 'Strong',
    priorityScore: 0,
    readiness: 0,
    gradient: 'from-purple-500/20 to-purple-900/40',
    image: 'https://images.unsplash.com/photo-1532187875605-2fe358711e24?auto=format&fit=crop&q=80&w=800',
    examDate: '2026-08-01',
    notes: 'Weekly: Homework, Paper Review, Past Lesson Review, Missed Lesson Learning.',
    weeklyTasks: [
      { id: 'c1', title: 'Homework', completed: false },
      { id: 'c2', title: 'Paper Review (with past papers)', completed: false },
      { id: 'c3', title: 'Past Lesson Review', completed: false },
      { id: 'c4', title: 'Missed Lesson Learning & Practice (missed recording watch)', completed: false },
    ],
    topics: [
      { id: 'c1', title: '01. Atomic Structure', mastery: 90, image: 'https://images.unsplash.com/photo-1532187875605-2fe358711e24?auto=format&fit=crop&q=80&w=400' },
      { id: 'c2', title: '02. Structure & Bonding', mastery: 80, image: 'https://images.unsplash.com/photo-1532187875605-2fe358711e24?auto=format&fit=crop&q=80&w=400' },
      { id: 'c3', title: '03. Chemical Calculations', mastery: 75, image: 'https://images.unsplash.com/photo-1532187875605-2fe358711e24?auto=format&fit=crop&q=80&w=400' },
      { id: 'c4', title: '04. Gaseous State', mastery: 70, image: 'https://images.unsplash.com/photo-1532187875605-2fe358711e24?auto=format&fit=crop&q=80&w=400' },
      { id: 'c5', title: '05. Energetics', mastery: 60, image: 'https://images.unsplash.com/photo-1532187875605-2fe358711e24?auto=format&fit=crop&q=80&w=400' },
      { id: 'c6', title: '06. Chemistry of Elements', mastery: 50, image: 'https://images.unsplash.com/photo-1532187875605-2fe358711e24?auto=format&fit=crop&q=80&w=400' },
      { id: 'c7', title: '07. Organic Chemistry', mastery: 45, image: 'https://images.unsplash.com/photo-1532187875605-2fe358711e24?auto=format&fit=crop&q=80&w=400' },
      { id: 'c8', title: '08. Physical Chemistry', mastery: 40, image: 'https://images.unsplash.com/photo-1532187875605-2fe358711e24?auto=format&fit=crop&q=80&w=400' },
      { id: 'c9', title: '09. Inorganic Chemistry', mastery: 55, image: 'https://images.unsplash.com/photo-1532187875605-2fe358711e24?auto=format&fit=crop&q=80&w=400' },
      { id: 'c10', title: '10. Industrial Chemistry', mastery: 65, image: 'https://images.unsplash.com/photo-1532187875605-2fe358711e24?auto=format&fit=crop&q=80&w=400' },
      { id: 'c11', title: '11. Environmental Chem', mastery: 70, image: 'https://images.unsplash.com/photo-1532187875605-2fe358711e24?auto=format&fit=crop&q=80&w=400' },
    ]
  }
];

export const WEEKLY_BASE_SCHEDULE: WeeklySchedule = {
  Monday: [
    { id: 'm1', time: '04:30 AM – 06:30 AM', description: 'Deep Work: Pure Maths (core practice)', type: 'study' },
    { id: 'm2', time: '06:30 AM – 07:00 AM', description: 'Breakfast', type: 'break' },
    { id: 'm3', time: '07:00 AM – 01:00 PM', description: 'Chemistry Main Revision', type: 'tuition' },
    { id: 'm4', time: '01:00 PM – 02:00 PM', description: 'Lunch + rest', type: 'rest' },
    { id: 'm5', time: '02:00 PM – 03:30 PM', description: 'Deep Work: Chemistry conversion (tutorial Qs)', type: 'study' },
    { id: 'm6', time: '03:30 PM – 04:00 PM', description: 'Break', type: 'break' },
    { id: 'm7', time: '04:00 PM – 07:00 PM', description: 'Combined Maths', type: 'tuition' },
    { id: 'm8', time: '07:00 PM – 07:45 PM', description: 'Dinner', type: 'break' },
    { id: 'm9', time: '07:45 PM – 09:45 PM', description: 'Deep Work: Maths conversion (Pure + Applied)', type: 'study' },
    { id: 'm10', time: '09:45 PM – 10:20 PM', description: 'Physics formulas/definitions + 3 short Qs', type: 'study' },
    { id: 'm11', time: '10:20 PM – 10:40 PM', description: 'Error log (Maths + Chem)', type: 'study' },
  ],
  Tuesday: [
    { id: 't1', time: '04:30 AM – 06:30 AM', description: 'Deep Work: Pure Maths (algebra/calculus/trig)', type: 'study' },
    { id: 't2', time: '06:30 AM – 07:00 AM', description: 'Breakfast', type: 'break' },
    { id: 't3', time: '07:00 AM – 09:00 AM', description: 'Deep Work: Physics (concept + examples)', type: 'study' },
    { id: 't4', time: '09:00 AM – 09:30 AM', description: 'Break', type: 'break' },
    { id: 't5', time: '09:30 AM – 11:30 AM', description: 'Deep Work: Applied Maths (Mechanics / Stats)', type: 'study' },
    { id: 't6', time: '11:30 AM – 01:00 PM', description: 'Lunch + rest', type: 'rest' },
    { id: 't7', time: '01:00 PM – 03:00 PM', description: 'Deep Work: Physics past-paper Qs (timed)', type: 'study' },
    { id: 't8', time: '03:00 PM – 03:30 PM', description: 'Break', type: 'break' },
    { id: 't9', time: '03:30 PM – 05:00 PM', description: 'Deep Work: Timed Maths (Pure/Applied)', type: 'study' },
    { id: 't10', time: '05:00 PM – 06:00 PM', description: 'Dinner', type: 'break' },
    { id: 't11', time: '06:00 PM – 07:30 PM', description: 'Marking + corrections (from timed Maths)', type: 'study' },
    { id: 't12', time: '07:30 PM – 10:30 PM', description: 'Physics Rapid Session', type: 'tuition' },
    { id: 't13', time: '10:30 PM – 11:00 PM', description: 'Error log redo (Maths + Physics)', type: 'study' },
  ],
  Wednesday: [
    { id: 'w1', time: '04:30 AM – 06:30 AM', description: 'Deep Work: Applied Maths (Stats)', type: 'study' },
    { id: 'w2', time: '06:30 AM – 07:00 AM', description: 'Breakfast', type: 'break' },
    { id: 'w3', time: '07:00 AM – 01:00 PM', description: 'Chemistry Rapid Session', type: 'tuition' },
    { id: 'w4', time: '01:00 PM – 03:00 PM', description: 'Deep Work: Pure Maths (weak-area rebuild)', type: 'study' },
    { id: 'w5', time: '03:00 PM – 04:00 PM', description: 'Break', type: 'break' },
    { id: 'w6', time: '04:00 PM – 06:00 PM', description: 'Deep Work: Physics (past-paper set)', type: 'study' },
    { id: 'w7', time: '06:00 PM – 07:00 PM', description: 'Dinner', type: 'break' },
    { id: 'w8', time: '07:00 PM – 09:30 PM', description: 'Chemistry Extra Session', type: 'tuition' },
    { id: 'w9', time: '09:30 PM – 10:15 PM', description: 'Chemistry mini-conversion (5–10 Qs)', type: 'study' },
    { id: 'w10', time: '10:15 PM – 10:35 PM', description: 'Error log (Chem)', type: 'study' },
  ],
  Thursday: [
    { id: 'th1', time: '04:30 AM – 06:30 AM', description: 'Deep Work: Pure Maths (practice)', type: 'study' },
    { id: 'th2', time: '06:30 AM – 07:30 AM', description: 'Breakfast + buffer', type: 'break' },
    { id: 'th3', time: '07:30 AM – 01:00 PM', description: 'Physics', type: 'tuition' },
    { id: 'th4', time: '01:00 PM – 02:00 PM', description: 'Lunch + rest', type: 'rest' },
    { id: 'th5', time: '02:00 PM – 04:00 PM', description: 'Deep Work: Physics conversion (lesson Qs)', type: 'study' },
    { id: 'th6', time: '04:00 PM – 04:30 PM', description: 'Break', type: 'break' },
    { id: 'th7', time: '04:30 PM – 06:30 PM', description: 'Deep Work: Applied Maths (Mechanics)', type: 'study' },
    { id: 'th8', time: '06:30 PM – 07:30 PM', description: 'Dinner', type: 'break' },
    { id: 'th9', time: '07:30 PM – 09:00 PM', description: 'Deep Work: Pure Maths (timed mini-set)', type: 'study' },
    { id: 'th10', time: '09:00 PM – 09:45 PM', description: 'Chemistry (light: definitions/reactions)', type: 'study' },
    { id: 'th11', time: '09:45 PM – 10:15 PM', description: 'Error log (Physics + Maths)', type: 'study' },
  ],
  Friday: [
    { id: 'f1', time: '04:30 AM – 06:30 AM', description: 'Deep Work: Physics (problems + formulae)', type: 'study' },
    { id: 'f2', time: '06:30 AM – 08:00 AM', description: 'Breakfast + buffer', type: 'break' },
    { id: 'f3', time: '08:00 AM – 02:00 PM', description: 'Combined Maths', type: 'tuition' },
    { id: 'f4', time: '02:00 PM – 03:00 PM', description: 'Lunch + rest', type: 'rest' },
    { id: 'f5', time: '03:00 PM – 05:00 PM', description: 'Deep Work: Maths conversion (Pure + Applied)', type: 'study' },
    { id: 'f6', time: '05:00 PM – 05:30 PM', description: 'Break', type: 'break' },
    { id: 'f7', time: '05:30 PM – 07:00 PM', description: 'Deep Work: Physics timed section', type: 'study' },
    { id: 'f8', time: '07:00 PM – 07:45 PM', description: 'Dinner', type: 'break' },
    { id: 'f9', time: '07:45 PM – 09:15 PM', description: 'Chemistry (question set)', type: 'study' },
    { id: 'f10', time: '09:15 PM – 10:00 PM', description: 'Corrections + error log (Physics + Maths)', type: 'study' },
  ],
  Saturday: [
    { id: 's1', time: '04:30 AM – 07:30 AM', description: 'Deep Work: Big timed paper block', type: 'study' },
    { id: 's2', time: '07:30 AM – 08:30 AM', description: 'Breakfast', type: 'break' },
    { id: 's3', time: '08:30 AM – 11:30 AM', description: 'Deep Work: Deep corrections + error log', type: 'study' },
    { id: 's4', time: '11:30 AM – 01:00 PM', description: 'Lunch/rest', type: 'rest' },
    { id: 's5', time: '01:00 PM – 03:00 PM', description: 'Deep Work: Weak-topic fixing', type: 'study' },
    { id: 's6', time: '03:00 PM – 04:00 PM', description: 'Break', type: 'break' },
    { id: 's7', time: '04:00 PM – 06:00 PM', description: 'Deep Work: Physics / Maths focus', type: 'study' },
    { id: 's8', time: '06:00 PM – 07:00 PM', description: 'Dinner', type: 'break' },
    { id: 's9', time: '07:00 PM – 08:00 PM', description: 'Light review + prep questions', type: 'study' },
    { id: 's10', time: '08:00 PM – 10:30 PM', description: 'Combined Maths', type: 'tuition' },
    { id: 's11', time: '10:30 PM – 11:00 PM', description: 'Mini conversion (Pure + Applied)', type: 'study' },
  ],
  Sunday: [
    { id: 'su1', time: '05:30 AM – 07:30 AM', description: 'Deep Work: Chemistry (revision + Qs)', type: 'study' },
    { id: 'su2', time: '07:30 AM – 08:30 AM', description: 'Breakfast', type: 'break' },
    { id: 'su3', time: '08:30 AM – 10:30 AM', description: 'Deep Work: Pure Maths (practice)', type: 'study' },
    { id: 'su4', time: '10:30 AM – 11:00 AM', description: 'Break', type: 'break' },
    { id: 'su5', time: '11:00 AM – 01:00 PM', description: 'Deep Work: Applied Maths (Stats)', type: 'study' },
    { id: 'su6', time: '01:00 PM – 03:00 PM', description: 'Lunch + rest', type: 'rest' },
    { id: 'su7', time: '03:00 PM – 05:00 PM', description: 'Weekly Catch-up & Missed Work (Previous weeks)', type: 'study' },
    { id: 'su8', time: '05:00 PM – 07:00 PM', description: 'Combined Maths', type: 'tuition' },
    { id: 'su9', time: '07:00 PM – 07:30 PM', description: 'Dinner', type: 'break' },
    { id: 'su10', time: '07:30 PM – 10:30 PM', description: 'Physics', type: 'tuition' },
    { id: 'su11', time: '10:30 PM – 11:00 PM', description: 'Physics quick conversion', type: 'study' },
  ],
};

export const INITIAL_BADGES: Badge[] = [
  { id: 'b1', title: 'Early Bird', description: 'Complete 5 study sessions before 7 AM', icon: 'Sunrise', type: 'sessions', requirement: 5 },
  { id: 'b2', title: 'Consistent Learner', description: 'Maintain a 3-day study streak', icon: 'Flame', type: 'streak', requirement: 3 },
  { id: 'b3', title: 'Maths Wizard', description: 'Achieve 80% mastery in 5 Maths topics', icon: 'Calculator', type: 'mastery', requirement: 5 },
  { id: 'b4', title: 'Physics Pro', description: 'Achieve 80% mastery in 5 Physics topics', icon: 'Zap', type: 'mastery', requirement: 5 },
  { id: 'b5', title: 'Chemistry Expert', description: 'Achieve 80% mastery in 5 Chemistry topics', icon: 'Beaker', type: 'mastery', requirement: 5 },
  { id: 'b6', title: 'Study Marathon', description: 'Complete 10 hours of total study time', icon: 'Timer', type: 'time', requirement: 600 },
  { id: 'b7', title: 'Centurion', description: 'Complete 100 study sessions', icon: 'Trophy', type: 'sessions', requirement: 100 },
  { id: 'b8', title: 'Unstoppable', description: 'Maintain a 7-day study streak', icon: 'Shield', type: 'streak', requirement: 7 },
];

export const INITIAL_TASKS = [
  {
    id: 'dt-maths-1',
    title: 'Maths Practice (Deep Work)',
    description: 'Intensive problem solving and concept mastery',
    frequency: 'Daily',
    completed: false,
    subjectId: 'maths',
    createdAt: new Date().toISOString(),
    impact: 9,
    effort: 8
  },
  {
    id: 'dt-physics-1',
    title: 'Physics MCQ Book & Review',
    description: 'Complete daily MCQ set and review errors',
    frequency: 'Daily',
    completed: false,
    subjectId: 'physics',
    createdAt: new Date().toISOString(),
    impact: 8,
    effort: 7
  },
  {
    id: 'dt-chem-1',
    title: 'Chemistry MCQ',
    description: 'Daily chemistry multiple choice questions',
    frequency: 'Daily',
    completed: false,
    subjectId: 'chemistry',
    createdAt: new Date().toISOString(),
    impact: 7,
    effort: 6
  },
  {
    id: 'dt-recording-1',
    title: 'Past Recording Review',
    description: 'Review past recordings for Chemistry, Physics, or Combined Maths',
    frequency: 'Daily',
    completed: false,
    createdAt: new Date().toISOString(),
    impact: 6,
    effort: 5
  },
  // Weekly Tasks - Chemistry
  {
    id: 'wt-chem-1',
    title: 'Chemistry: Homework',
    frequency: 'Weekly',
    completed: false,
    subjectId: 'chemistry',
    createdAt: new Date().toISOString(),
    impact: 8,
    effort: 6
  },
  {
    id: 'wt-chem-2',
    title: 'Chemistry: Paper Review (with past papers)',
    frequency: 'Weekly',
    completed: false,
    subjectId: 'chemistry',
    createdAt: new Date().toISOString(),
    impact: 9,
    effort: 8
  },
  {
    id: 'wt-chem-3',
    title: 'Chemistry: Past Lesson Review',
    frequency: 'Weekly',
    completed: false,
    subjectId: 'chemistry',
    createdAt: new Date().toISOString(),
    impact: 7,
    effort: 5
  },
  {
    id: 'wt-chem-4',
    title: 'Chemistry: Missed Lesson Learning & Practice (missed recording watch)',
    frequency: 'Weekly',
    completed: false,
    subjectId: 'chemistry',
    createdAt: new Date().toISOString(),
    impact: 8,
    effort: 7
  },
  // Weekly Tasks - Physics
  {
    id: 'wt-physics-1',
    title: 'Physics: Homework',
    frequency: 'Weekly',
    completed: false,
    subjectId: 'physics',
    createdAt: new Date().toISOString(),
    impact: 8,
    effort: 6
  },
  {
    id: 'wt-physics-2',
    title: 'Physics: Paper Review (with past papers)',
    frequency: 'Weekly',
    completed: false,
    subjectId: 'physics',
    createdAt: new Date().toISOString(),
    impact: 9,
    effort: 8
  },
  {
    id: 'wt-physics-3',
    title: 'Physics: Past Lesson Review',
    frequency: 'Weekly',
    completed: false,
    subjectId: 'physics',
    createdAt: new Date().toISOString(),
    impact: 7,
    effort: 5
  },
  {
    id: 'wt-physics-4',
    title: 'Physics: Missed Lesson Learning & Practice (missed recording watch)',
    frequency: 'Weekly',
    completed: false,
    subjectId: 'physics',
    createdAt: new Date().toISOString(),
    impact: 8,
    effort: 7
  },
  {
    id: 'wt-physics-5',
    title: 'Physics: Practical Lesson Learning & Practice',
    frequency: 'Weekly',
    completed: false,
    subjectId: 'physics',
    createdAt: new Date().toISOString(),
    impact: 7,
    effort: 6
  },
  // Weekly Tasks - Combined Maths
  {
    id: 'wt-maths-1',
    title: 'Combined Maths: Homework',
    frequency: 'Weekly',
    completed: false,
    subjectId: 'maths',
    createdAt: new Date().toISOString(),
    impact: 8,
    effort: 6
  },
  {
    id: 'wt-maths-2',
    title: 'Combined Maths: Paper Review (with past papers)',
    frequency: 'Weekly',
    completed: false,
    subjectId: 'maths',
    createdAt: new Date().toISOString(),
    impact: 9,
    effort: 8
  },
  {
    id: 'wt-maths-3',
    title: 'Combined Maths: Past Lesson Review',
    frequency: 'Weekly',
    completed: false,
    subjectId: 'maths',
    createdAt: new Date().toISOString(),
    impact: 7,
    effort: 5
  },
  {
    id: 'wt-maths-4',
    title: 'Combined Maths: Missed Lesson Learning & Practice (missed recording watch)',
    frequency: 'Weekly',
    completed: false,
    subjectId: 'maths',
    createdAt: new Date().toISOString(),
    impact: 8,
    effort: 7
  }
];
